apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aeroflow-workspace
  labels:
    {{- include "aeroflow.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
