apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aeroflow.fullname" . }}-jwt
  labels:
    {{- include "aeroflow.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.aeroflow.jwtSecret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aeroflow.fullname" . }}-postgresql
  labels:
    {{- include "aeroflow.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
