/// Generate NACA0018 VAWT blade STL
/// Usage: rustc gen_stl.rs -O && ./gen_stl
/// Output: naca0018_vawt.stl (current directory)
use std::fs::File;
use std::io::Write;

fn main() {
    let chord = 0.3f32;
    let span = 1.0f32;
    let n = 60;

    // NACA 0018: symmetric, 18% thickness
    let thick = |x: f32| -> f32 {
        let t = 0.18 / 0.20;
        t * (0.2969 * x.sqrt() - 0.1260 * x - 0.3516 * x * x + 0.2843 * x * x * x - 0.1015 * x * x * x * x)
    };

    // Build profile points: upper LE->TE, then lower TE->LE
    let mut pts: Vec<(f32, f32)> = Vec::with_capacity(2 * n + 2);
    for i in 0..=n {
        let x = i as f32 / n as f32;
        let yt = thick(x);
        pts.push((x * chord, yt * chord));
    }
    for i in (0..=n).rev() {
        let x = i as f32 / n as f32;
        let yt = thick(x);
        pts.push((x * chord, -yt * chord));
    }

    // Build triangles: extrude profile from z=0 to z=span
    // For each edge (i, i+1) around the profile, create 2 triangles (front + back)
    let mut tri_data: Vec<f32> = Vec::new();
    for i in 0..pts.len() {
        let j = if i + 1 < pts.len() { i + 1 } else { 0 }; // wrap around
        let (ax, ay) = pts[i];
        let (bx, by) = pts[j];
        // Front face (z=0), CCW winding
        tri_data.extend_from_slice(&[ax, ay, 0.0, bx, by, 0.0, ax, ay, span]);
        // Back face (z=span), reversed winding for outward normal
        tri_data.extend_from_slice(&[ax, ay, span, bx, by, 0.0, bx, by, span]);
    }

    let count = tri_data.len() / 9;

    // Write binary STL
    let mut f = File::create("naca0018_vawt.stl").expect("create file");

    // 80-byte header
    let mut header = [0u8; 80];
    let msg = b"NACA0018 VAWT Blade - Generated by AeroFlow Agent";
    header[..msg.len()].copy_from_slice(msg);
    f.write_all(&header).unwrap();
    f.write_all(&(count as u32).to_le_bytes()).unwrap();

    for i in 0..count {
        let ax = tri_data[i * 9];
        let ay = tri_data[i * 9 + 1];
        let az = tri_data[i * 9 + 2];
        let bx = tri_data[i * 9 + 3];
        let by = tri_data[i * 9 + 4];
        let bz = tri_data[i * 9 + 5];
        let cx = tri_data[i * 9 + 6];
        let cy = tri_data[i * 9 + 7];
        let cz = tri_data[i * 9 + 8];

        // Compute normal via cross product
        let nx = (ay - cy) * (bz - cz) - (az - cz) * (by - cy);
        let ny = (az - cz) * (bx - cx) - (ax - cx) * (bz - cz);
        let nz = (ax - cx) * (by - cy) - (ay - cy) * (bx - cx);
        let len = (nx * nx + ny * ny + nz * nz).sqrt();
        let (nx, ny, nz) = if len > 0.0 { (nx/len, ny/len, nz/len) } else { (0.0, 0.0, 0.0) };

        f.write_all(&nx.to_le_bytes()).unwrap();
        f.write_all(&ny.to_le_bytes()).unwrap();
        f.write_all(&nz.to_le_bytes()).unwrap();
        f.write_all(&ax.to_le_bytes()).unwrap();
        f.write_all(&ay.to_le_bytes()).unwrap();
        f.write_all(&az.to_le_bytes()).unwrap();
        f.write_all(&bx.to_le_bytes()).unwrap();
        f.write_all(&by.to_le_bytes()).unwrap();
        f.write_all(&bz.to_le_bytes()).unwrap();
        f.write_all(&cx.to_le_bytes()).unwrap();
        f.write_all(&cy.to_le_bytes()).unwrap();
        f.write_all(&cz.to_le_bytes()).unwrap();
        f.write_all(&0u16.to_le_bytes()).unwrap(); // attribute
    }

    println!("✅ NACA0018 VAWT blade: naca0018_vawt.stl ({} triangles, {:.1} KB)", count, (count * 50) as f32 / 1024.0);
}
