import React, { useState } from 'react';
import { BookOpen, HelpCircle, Code, Award, Check } from 'lucide-react';

export default function DocGuide() {
  const [copiedEqId, setCopiedEqId] = useState<string | null>(null);

  const equations = [
    {
      id: 'reynolds-eq',
      title: 'Reynolds Number (Re)',
      formula: 'Re = (ρ * V * L) / μ',
      desc: 'Predicts fluid flow patterns (laminar vs. turbulent) based on density ρ, free-stream velocity V, chord length L, and dynamic viscosity μ.'
    },
    {
      id: 'lift-eq',
      title: 'Lift Coefficient (Cl)',
      formula: 'Cl = L_force / (0.5 * ρ * V² * A)',
      desc: 'Dimensionless coefficient that relates lift generated by an airfoil to fluid dynamic pressure and planform wing area A.'
    },
    {
      id: 'drag-eq',
      title: 'Induced Drag (Cdi)',
      formula: 'Cdi = Cl² / (π * AR * e)',
      desc: 'Formulates pressure drag created by wingtip vortices, governed directly by Aspect Ratio (AR) and Oswald efficiency factor (e).'
    }
  ];

  const handleCopy = (eqId: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedEqId(eqId);
    setTimeout(() => setCopiedEqId(null), 1500);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Title & Header Banner */}
      <div className="border-b border-brand-border bg-white p-5 rounded-lg shadow-2xs">
        <h2 className="font-sans text-sm font-bold uppercase tracking-wider text-brand-text flex items-center gap-1.5">
          <BookOpen className="h-4.5 w-4.5 text-brand-primary" /> Aerodynamics Solver Reference Guide
        </h2>
        <p className="font-mono text-[10.5px] text-brand-text-muted mt-0.5">
          Mathematical foundations, meshing protocols, and fluid coefficient equations.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-5 lg:grid-cols-12">
        {/* Core Equations block - 7 col */}
        <div className="space-y-5 lg:col-span-8">
          <div className="rounded-lg border border-brand-border bg-white p-5 space-y-4 shadow-2xs">
            <h3 className="font-sans text-xs font-bold uppercase tracking-wider text-brand-text flex items-center gap-1.5">
              <Award className="h-4.5 w-4.5 text-brand-primary" /> Boundary Aerodynamics Equations
            </h3>
            <p className="font-sans text-xs text-brand-text-muted leading-relaxed">
              These governing equations form the core mathematical constraints of the AeroFlow steady-state solvers. Click on any equation to copy the LaTeX code snippet directly to your spreadsheet.
            </p>

            <div className="space-y-3.5">
              {equations.map((eq) => (
                <div key={eq.id} className="rounded-lg border border-brand-bg bg-brand-bg/40 p-4 space-y-2">
                  <div className="flex items-center justify-between">
                    <h4 className="font-sans text-xs font-bold text-brand-text">{eq.title}</h4>
                    <button
                      onClick={() => handleCopy(eq.id, eq.formula)}
                      className="rounded border border-brand-border bg-white hover:bg-brand-container px-2.5 py-1 text-[10px] font-mono font-bold text-brand-text-muted transition-colors"
                    >
                      {copiedEqId === eq.id ? (
                        <span className="text-emerald-600 flex items-center gap-1">
                          <Check className="h-3 w-3" /> Copied!
                        </span>
                      ) : (
                        <span>Copy Code</span>
                      )}
                    </button>
                  </div>

                  <div className="rounded border bg-white py-3 text-center font-mono text-base font-bold text-brand-primary select-all">
                    {eq.formula}
                  </div>

                  <p className="font-sans text-[11px] text-brand-text-muted leading-relaxed">
                    {eq.desc}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Meshing guides definitions */}
          <div className="rounded-lg border border-brand-border bg-white p-5 space-y-4 shadow-2xs">
            <h3 className="font-sans text-xs font-bold uppercase tracking-wider text-brand-text flex items-center gap-1.5">
              <Code className="h-4.5 w-4.5 text-brand-accent animate-pulse" /> Navier-Stokes Solver Implementation Notes
            </h3>
            
            <div className="space-y-3 font-sans text-xs text-brand-text leading-relaxed">
              <p>
                AeroFlow utilizes high-density steady Navier-Stokes solvers based on the <strong>Reynolds-Averaged Navier-Stokes (RANS)</strong> model coupled with <strong>shear stress transport (SST) k-omega equations</strong>.
              </p>
              
              <div className="p-3 bg-brand-bg rounded-md font-mono text-[11px] text-brand-text-muted border-l-4 border-brand-primary">
                {`// Navier-Stokes steady state iteration schema:
function solveGridFluidStep(gridCell, velocityVector) {
  const pressureGradient = calculatePressureGradient(gridCell);
  const viscousDiffusion = calculateViscosityDiffusion(gridCell);
  
  // Update local momentum components
  gridCell.u += dt * ( -velocityVector.u * dUdx + viscousDiffusion.u - pressureGradient.x );
  gridCell.v += dt * ( -velocityVector.v * dVdy + viscousDiffusion.v - pressureGradient.y );
  
  return checkL2ConvergenceLimit(gridCell);
}`}
              </div>

              <p>
                For peak numerical stability, we recommend maintaining aspect ratios between 6.0 and 11.0 on commercial regional wing section profiles. Lower values (AR &lt; 3.0) can trigger severe secondary shock formations at high Mach speeds (&gt; M 0.82) leading to subsonic flow detachment.
              </p>
            </div>
          </div>
        </div>

        {/* Sidebar Help desk list - 4 col */}
        <div className="space-y-5 lg:col-span-4">
          <div className="rounded-lg border border-brand-border bg-white p-4 space-y-4 shadow-2xs">
            <span className="font-sans font-bold text-[10px] uppercase tracking-wide text-brand-text-muted flex items-center gap-1.5">
              <HelpCircle className="h-4 w-4 text-brand-primary" /> Technical Term Glossary
            </span>

            <ul className="space-y-3.5 divide-y divide-brand-bg font-sans text-xs leading-tight">
              <li className="pt-3 first:pt-0">
                <span className="font-bold text-brand-text">Camber</span>
                <p className="mt-1 text-[11px] text-brand-text-muted leading-relaxed">The asymmetry between the upper and lower curves of an airfoil section.</p>
              </li>
              <li className="pt-3">
                <span className="font-bold text-brand-text">Wave Drag</span>
                <p className="mt-1 text-[11px] text-brand-text-muted leading-relaxed">Resistance generated by shock waves on aircraft wings flying at supersonic/transonic velocities.</p>
              </li>
              <li className="pt-3">
                <span className="font-bold text-brand-text">Boundary Layer</span>
                <p className="mt-1 text-[11px] text-brand-text-muted leading-relaxed">The fluid layer immediately adjacent to the wing skin where viscosity forces dominate flow speed.</p>
              </li>
              <li className="pt-3">
                <span className="font-bold text-brand-text">Aspect Ratio (AR)</span>
                <p className="mt-1 text-[11px] text-brand-text-muted leading-relaxed">The ratio of wing span to its mean chord length. Controls performance and glide lift.</p>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
