use std::path::Path;
use tracing::info;

pub async fn execute(case_path: &Path) -> anyhow::Result<()> {
    info!("Generating report for case: {:?}", case_path);

    if !case_path.join("system/controlDict").exists() {
        anyhow::bail!("Not a valid case directory: {:?}", case_path);
    }

    let report_dir = case_path.join("report");

    // Read force coefficients from postProcessing
    let (cl, cd) = match std::fs::read_to_string(case_path.join("postProcessing/forceCoeffs/0/coefficient.dat")) {
        Ok(data) => {
            let last_line = data.lines().filter(|l| !l.starts_with('#')).last().unwrap_or("");
            let parts: Vec<&str> = last_line.split_whitespace().collect();
            if parts.len() >= 4 {
                (parts[3].parse::<f64>().unwrap_or(0.0), parts[1].parse::<f64>().unwrap_or(0.0))
            } else {
                (0.0, 0.0)
            }
        }
        Err(_) => (0.0, 0.0),
    };

    // Read cell count from mesh owner file
    let n_cells = match std::fs::metadata(case_path.join("constant/polyMesh/owner")) {
        Ok(m) => m.len() / 4,
        Err(_) => 0,
    };

    // Generate simple HTML report
    std::fs::create_dir_all(&report_dir)?;
    let html = format!(
        r#"<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>AeroFlow Report</title>
<style>body{{font-family:sans-serif;margin:2em;background:#f5f5f5}}
h1{{color:#1a1a2e}}table{{border-collapse:collapse;width:100%}}
th,td{{text-align:left;padding:8px;border-bottom:1px solid #ddd}}
th{{background:#1a1a2e;color:white}}.ok{{color:green}}.warn{{color:orange}}</style></head>
<body>
<h1>AeroFlow Agent — CFD Report</h1>
<p>Developer: Jettanakorn Pengsiri by JFOX Aircraft Co., Ltd.</p>
<table><tr><th>Metric</th><th>Value</th><th>Status</th></tr>
<tr><td>Case</td><td>{case}</td><td class="ok">✓</td></tr>
<tr><td>Mesh Cells</td><td>{cells}</td><td class="ok">✓</td></tr>
<tr><td>Lift Coefficient (Cl)</td><td>{cl:.6}</td><td class="ok">✓</td></tr>
<tr><td>Drag Coefficient (Cd)</td><td>{cd:.6}</td><td class="ok">✓</td></tr>
</table>
<p>Generated by AeroFlow Agent v0.1.0 &mdash; JFOX Aircraft Co., Ltd.</p>
</body></html>"#,
        case = case_path.display(),
        cells = n_cells,
        cl = cl,
        cd = cd,
    );

    std::fs::write(report_dir.join("index.html"), html)?;
    println!("\n✓ Report generated for '{:?}'", case_path);
    println!("  Path: {:?}/index.html", report_dir);

    Ok(())
}
